on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate QR Code
        run: python generate_qr_code.py "Hello, World!"
        continue-on-error: true

      - name: Scan QR Code
        run: python scan_qr_code.py
        continue-on-error: true

    # Define artifacts at the job level, not inside each step
    artifacts:
      paths:
        - qrcode.png
        - generated_image.png
