pipeline:
  steps:
    - name: Generate QR Code
      command: |
        python generate_qr_code.py "Hello, World!"
      artifact_paths:
        - qrcode.png

    - name: Scan QR Code
      command: |
        python scan_qr_code.py
      artifact_paths:
        - generated_image.png
