name: QR Code Generator and Scanner

on:
  push:
    branches:
      - main

jobs:

  qr-code:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install qrcode opencv-python numpy
    - name: Run QR Code script
      run: |
        python qr_code_script.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: qr-code-images
        path: |
          qrcode.png
          generated_image.png
